# Generated by Django 5.1.3 on 2024-12-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_product_is_in_stock_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='businessuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cashback_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
