# Generated by Django 5.1.3 on 2024-12-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='wholesale_price',
        ),
    ]
