# Generated by Django 5.1.3 on 2024-12-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_businessuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessuser',
            name='address',
        ),
    ]
