# Generated by Django 5.1.3 on 2024-12-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_remove_businessuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
